on: push
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}    
    steps:      
    - if: runner.os == 'Windows'
      run: ping -n 5000000 localhost      
    - if: runner.os != 'Windows'
      run: ping -c 5000000 localhost
